#服务端配置
server:
  port: 8091   #端口号
  servlet:
    session:
      timeout: 120m #设置过期时间为120分钟




mybatis:
  mapper-locations: classpath*:mapper/*.xml #扫描mybatis的mapper.xml文件
  type-aliases-package: com.lcvc.new_coronavirus_report.model #起别名，指向实体类的位置，可省略写mybatis的xml中的resultType的全路径，取代<typeAlias alias="Admin" type="com.ljy.maven_github_ssm.model.Admin"/>

spring:
  devtools:
    restart:
      enabled: true  #开启自动启动
#  mvc:
#    static-path-pattern: /static/**
  thymeleaf:
    cache: true #缓存（开发时设置为false）
  #jdbc配置，springboot默认会把spring.datasource开头的信息收纳，进行DataSource对象的配置，进而进行sqlSessionFactory的配置等相关数据库连接的配置，从而省略了application.xml中的相关
  datasource:
      url: jdbc:mysql://localhost:3306/new_coronavirus_report?characterEncoding=utf-8&serverTimezone=CTT
      username: lcvc
      password: lcvc123456
      driverClassName: com.mysql.cj.jdbc.Driver
      druid:
        #初始化大小
        initialSize: 5
        #最小值
        minIdle: 5
        #最大值
        maxActive: 20
        #最大等待时间，配置获取连接等待超时，时间单位都是毫秒ms
        maxWait: 60000
        #配置间隔多久才进行一次检测，检测需要关闭的空闲连接
        timeBetweenEvictionRunsMillis: 60000
        #配置一个连接在池中最小生存的时间
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，
        #'wall'用于防火墙，SpringBoot中没有log4j，我改成了log4j2
        filters: stat,wall,log4j2
        #最大PSCache连接
        maxPoolPreparedStatementPerConnectionSize: 20
        useGlobalDataSourceStat: true
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
        # 配置StatFilter
        web-stat-filter:
          #默认为false，设置为true启动
          enabled: true
          url-pattern: "/*"
          exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
        #配置StatViewServlet
        stat-view-servlet:
          url-pattern: "/druid/*"
          #启用
          enabled: true
  jackson:    #设置全局json格式
    date-format: yyyy-MM-dd HH:mm:ss   #将日期类型设置为字符串表示
    time-zone: GMT+8

  mvc: #针对form表单格式
    dateFormat: yyyy-MM-dd HH:mm:ss #将日期类型设置为字符串表示
  servlet:
    multipart:
      maxFileSize: 100MB #单个上传文件的最大限制
      maxRequestSize: 100MB  #所有上传文件的最大限制
#控制台打印sql语句
logging:
  file: target/log/new_coronavirus_report.log
  level:
    com.lcvc.new_coronavirus_report: error
    org.springframework: error
# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  #excludes: /system/notice/*
  excludes:
  # 匹配链接
  #urlPatterns: /system/*,/monitor/*,/tool/*
  urlPatterns: /api/*